# Generated by Django 5.2.1 on 2025-11-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_challenge_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_false',
            field=models.BooleanField(default=False),
        ),
    ]
